### PR TITLE
ecs resource code

### PR DESCRIPTION
**Pull request by drii-cavalcanti**
there are some variables which need to be completed. Please, if anyone knows how to complete them feel free to do it.

### CODE REVIEW

**Comment by starkmatt** [comment]
Hey Adriana!
Nice,
Would you mind explaining what's going on here ?
Also where abouts did you need some help with the variables, perhaps I can help!

**Comment by drii-cavalcanti** [comment]
> Hey Adriana!
> Nice,
> Would you mind explaining what's going on here ?
> Also where abouts did you need some help with the variables, perhaps I can help!

Those variables have "TO DO" as value

**Comment by drii-cavalcanti** [comment]
closing this PR due to Marcio's commits

**Comment by drii-cavalcanti** [comment]
closing this PR due to Marcio's commits

**Pull request closed without merging**
